export const CLICK_UPDATE_STATUS_USER = 'CLICK_UPDATE_STATUS_USER';
export const NOTIFICATION_VALUE = 'NOTIFICATION_VALUE';
export const MINHA_CESTA_VALUE = 'MINHA_CESTA_VALUE';
export const CLICK_UPDATE_VALUE = 'CLICK_UPDATE_VALUE'